apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: devworkspace-gitconfig
objects:  
  - kind: Secret
    apiVersion: v1
    metadata:
      name: user-profile
      namespace: ${USERNAME}-devspaces
      labels:
        controller.devfile.io/mount-to-devworkspace: 'true'
        controller.devfile.io/watch-secret: 'true'
      annotations:
        controller.devfile.io/mount-as: file
        controller.devfile.io/mount-path: /config/user/profile
    stringData:
      email: ${USERNAME}@che
      name: ${USERNAME}
    type: Opaque
parameters:
- description: Username
  name: USERNAME              
