apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: che-cluster
  namespace: devspaces
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  components:
    imagePuller:
      enable: true
      spec:
        images: >-
          community-udi=quay.io/devfile/universal-developer-image@sha256:75034f0dad7a6df3db53e20fc3597b68f2311e556164d47aa9151d3b3584bbce;devspaces-machineexec-plugin-registry-image-gmxdecq=registry.redhat.io/devspaces/machineexec-rhel8@sha256:30dff710196f7061066932a69ca4d3f680d88c95e2883dd5809d43d3e4a8e39f;code-rhel8=registry.redhat.io/devspaces/code-rhel8@sha256:42da1996453b6594233a5772473a88f32c5c52191899c05b99032a70ce459534;idea-rhel8=registry.redhat.io/devspaces/idea-rhel8@sha256:ea2c269d7e8907a7cce68e554e0f6cede9f1f811b2dbfcea2b0ed67cd8709ca5;udi-rhel8=registry.redhat.io/devspaces/udi-rhel8@sha256:72762feb5ccea26dc7872877b9661fb34a295da05b96581d364c507a4923361e;project-clone=registry.redhat.io/devworkspace/devworkspace-project-clone-rhel8@sha256:7b562a39e7aa3e15063d5634ec9b4dd4a9041b6cde74e9ae3394104eb3e1b886;custom-udi=quay.io/marslan/rhte-camelk@sha256:190da1b16af02ff7258ecf363c5d601f567babf5c15fb1bcb2e7b08e4c3186e1
    devWorkspace:
      runningLimit: '61'
    cheServer:
      debug: false
      logLevel: INFO
    metrics:
      enable: true
    pluginRegistry:
     openVSXURL: "https://open-vsx.org"
  containerRegistry: {}
  devEnvironments:
    gatewayContainer:
      resources:
        limits:
          cpu: "4"
          memory: 5Gi
        request:
          cpu: "1"
          memory: 1Gi  
    secondsOfRunBeforeIdling: -1
    startTimeoutSeconds: 1200
    defaultNamespace:
      template: devspaces-<username>
    secondsOfInactivityBeforeIdling: -1
    storage:
      perWorkspaceStrategyPvcConfig:
        claimSize: 10Gi
      pvcStrategy: per-workspace
  networking: {}
