apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: che-cluster
  namespace: devspaces
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  components:
    imagePuller:
      enable: true
      spec:
        images: >-
          devspaces-theia-plugin-registry-image-gmxdecq=registry.redhat.io/devspaces/theia-rhel8@sha256:0f550ba6a88ca8e29bbba1c41829013f88208f47c169f9d1db911866285c684d;devspaces-theia-endpoint-devfile-registry-image-gmxdecq=registry.redhat.io/devspaces/theia-endpoint-rhel8@sha256:e1b120b445f5ac484ba90c04357a2b218e4c990bbdbedbcdb347565c29cb1ea8;devspaces-theia-endpoint-plugin-registry-image-gmxdecq=registry.redhat.io/devspaces/theia-endpoint-rhel8@sha256:e1b120b445f5ac484ba90c04357a2b218e4c990bbdbedbcdb347565c29cb1ea8;devspaces-theia-devfile-registry-image-gmxdecq=registry.redhat.io/devspaces/theia-rhel8@sha256:0f550ba6a88ca8e29bbba1c41829013f88208f47c169f9d1db911866285c684d;devspaces-machineexec-plugin-registry-image-gmxdecq=registry.redhat.io/devspaces/machineexec-rhel8@sha256:30dff710196f7061066932a69ca4d3f680d88c95e2883dd5809d43d3e4a8e39f;code-rhel8=registry.redhat.io/devspaces/code-rhel8@sha256:42da1996453b6594233a5772473a88f32c5c52191899c05b99032a70ce459534;idea-rhel8=registry.redhat.io/devspaces/idea-rhel8@sha256:ea2c269d7e8907a7cce68e554e0f6cede9f1f811b2dbfcea2b0ed67cd8709ca5;udi-rhel8=registry.redhat.io/devspaces/udi-rhel8@sha256:72762feb5ccea26dc7872877b9661fb34a295da05b96581d364c507a4923361e;project-clone=registry.redhat.io/devworkspace/devworkspace-project-clone-rhel8@sha256:7b562a39e7aa3e15063d5634ec9b4dd4a9041b6cde74e9ae3394104eb3e1b886;custom-udi=quay.io/marslan/rhte-camelk@sha256:190da1b16af02ff7258ecf363c5d601f567babf5c15fb1bcb2e7b08e4c3186e1
    devWorkspace:
      runningLimit: '60'
    cheServer:
      debug: false
      logLevel: INFO
    database:
      credentialsSecretName: postgres-credentials
      externalDb: false
      postgresDb: dbche
      postgresHostName: postgres
      postgresPort: '5432'
      pvc:
        claimSize: 1Gi
    metrics:
      enable: true
  containerRegistry: {}
  devEnvironments:
    secondsOfRunBeforeIdling: -1
    defaultNamespace:
      template: <username>-dev
    secondsOfInactivityBeforeIdling: -1
    storage:
      pvcStrategy: per-workspace
  networking: {}