apiVersion: sonatype.com/v1alpha1
kind: NexusRepo
metadata:
  name: example-nexusrepo
  namespace: nexus
spec:
  config:
    data: null
    enabled: false
    mountPath: /sonatype-nexus-conf
  deployment:
    additionalContainers: null
    additionalVolumeMounts: null
    additionalVolumes: null
    initContainers: null
    postStart:
      command: null
    preStart:
      command: null
    terminationGracePeriodSeconds: 120
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: false
    path: /
    rules: null
    tls:
      enabled: true
      secretName: nexus-tls
  nexus:
    dockerPort: 5003
    env:
    - name: INSTALL4J_ADD_VM_PARAMS
      value: -Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M -XX:+UnlockExperimentalVMOptions
        -XX:+UseCGroupMemoryLimitForHeap
    imageName: registry.connect.redhat.com/sonatype/nexus-repository-manager@sha256:599453a5b4b28491eab3e7c2867f83814d060e8c0e60ec25063d1f775406e740
    imagePullPolicy: IfNotPresent
    imagePullSecret: ""
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    nexusPort: 8081
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    service:
      type: NodePort
  nexusProxyRoute:
    annotations: null
    enabled: false
    labels: null
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    storageSize: 8Gi
  replicaCount: 1
  route:
    annotations: null
    enabled: false
    labels: null
    name: docker
    portName: docker
  secret:
    data: null
    enabled: false
    mountPath: /etc/secret-volume
    readOnly: true
  service:
    enabled: false
    ports:
    - name: nexus-service
      port: 80
      targetPort: 80
  statefulset:
    enabled: false
