apiVersion: v1
data:
  custom-ca-certificates.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDgzCCAmugAwIBAgIECKIoeTANBgkqhkiG9w0BAQsFADByMQswCQYDVQQGEwJD
    WjEUMBIGA1UECBMLUHJhaGEtWmFwYWQxEDAOBgNVBAcTB1Jldm5pY2UxFTATBgNV
    BAoTDERldlNwYWNlc1BPQzEMMAoGA1UECxMDTldHMRYwFAYDVQQDEw1BbnRvbiBH
    aWVydGxpMB4XDTIzMDEyOTE1NTAzOFoXDTIzMDQyOTE1NTAzOFowcjELMAkGA1UE
    BhMCQ1oxFDASBgNVBAgTC1ByYWhhLVphcGFkMRAwDgYDVQQHEwdSZXZuaWNlMRUw
    EwYDVQQKEwxEZXZTcGFjZXNQT0MxDDAKBgNVBAsTA05XRzEWMBQGA1UEAxMNQW50
    b24gR2llcnRsaTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKi+swQN
    B0PJbH+c5nKV+V2MIRGlRn7hjSw+emeV56pbbyRy81N9u1sb5b6uUyL7JjhE9cIp
    LChdNqVlRpuhHQU7UbX5G6/ZKgnNMPyQ3o7JQGiQULGUoq2FHOBfVFkPF68TM848
    eQ/yZr+AXHlDpGBhlZ0SQ0+8xrhCJBF9X1vgGcI98T33y74vAfjTCOjuiycV+L9u
    t1cXiakVLmB9q0Ju1wJ3NAxZssvbWADr4A/befPpBOhccvsZFblikunw2l/gkgdq
    UBCbP1Mnh5K0Yy5YeEgrM3QhsDxLapzufpTQuL4It4yzdwnLBJJnFnISQD2riAQw
    7t/upCQLZTlJBYcCAwEAAaMhMB8wHQYDVR0OBBYEFNE0WmuouLedBc/cQtzmRcAP
    T9OiMA0GCSqGSIb3DQEBCwUAA4IBAQA7+gyuEoiRp9XdumUlQxmvoj9DCxR4cOW9
    /D/TzCM+jqnE3jKVbFwAR8jA9AssjA8jqzoSutMzJk5vSCBQ/z/Bugyp4md4uxu0
    R52j2kyuIFUxWDuQKRwx79tzvXS3FeHCnB7jIRuN6dP0dHzWmUWXKuPaRI0NKV3z
    K+9/XQoJIW2JbffTZBId0Bx0lO9xP7TJZ9xGM0Clb1VVVQo6zkxNMdfR/fGGU/U8
    SL6/j2unaduRC/xXPPYKIxcCqODtc6Mlr4czVAWl8BIJmVc8FmSlM1efo7QEsVYz
    j2MCowaMGJMDUTdVj/HTTmWUULc1cHpXly5BEP1vtwCRwKoUoQDJ
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"    
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/component: ca-bundle
    app.kubernetes.io/part-of: che.eclipse.org
  name: custom-ca-certificates
  namespace: devspaces
