apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"   
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: devspaces-user-config
  namespace: namespace-config-operator
spec:
  labelSelector:
    matchLabels:
      app.kubernetes.io/component: workspaces-namespace
  templates:
  - excludedPaths:	
        - .status	
        - .spec.replicas	
        - .metadata  
    objectTemplate: |
        apiVersion: v1
        data:
          init-java8-truststore.sh: |
            #!/usr/bin/env bash
            keytool -importcert -noprompt -file /public-certs/custom-ca-certificates.custom-ca-certificates.pem -trustcacerts -keystore ~/.java/current/lib/security/cacerts -storepass changeit
        kind: ConfigMap
        metadata:
          annotations:
            controller.devfile.io/mount-as: subpath
            controller.devfile.io/mount-path: /home/user/
          labels:
            controller.devfile.io/mount-to-devworkspace: "true"
            controller.devfile.io/watch-configmap: "true"
          name: init-truststore
          namespace: {{ .Name }}   
  - excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas       
    objectTemplate: |
      kind: ConfigMap
      apiVersion: v1
      metadata:
        namespace: {{ .Name }} 
        name: settings-xml
        annotations:
          controller.devfile.io/mount-as: subpath
          controller.devfile.io/mount-path: /home/user/.m2
        labels:
          controller.devfile.io/mount-to-devworkspace: 'true'
          controller.devfile.io/watch-configmap: 'true'
      data:
        settings.xml: |
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <localRepository />
            <interactiveMode />
            <offline />
            <pluginGroups />
            <mirrors />
            <proxies />
            <profiles>
                <profile>
                  <id>redhat</id>
                  <repositories>
                      <repository>
                        <id>rh-ga</id>
                        <name>Red Hat public maven repo</name>
                        <url>https://maven.repository.redhat.com/ga/</url>
                        <releases>
                            <enabled>true</enabled>
                            <updatePolicy>never</updatePolicy>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                      </repository>
                      <repository>
                        <id>jenkins-ga</id>
                        <name>jenkins repo</name>
                        <url>https://repo.jenkins-ci.org/releases/</url>
                        <releases>
                            <enabled>true</enabled>
                            <updatePolicy>never</updatePolicy>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                      </repository>
                  </repositories>
                  <pluginRepositories>
                      <pluginRepository>
                        <id>rh-ga</id>
                        <name>Red Hat public maven repo</name>
                        <url>https://maven.repository.redhat.com/ga</url>
                        <releases>
                            <enabled>true</enabled>
                            <updatePolicy>never</updatePolicy>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                      </pluginRepository>
                  </pluginRepositories>
                </profile>
            </profiles>
            <activeProfiles>
                <activeProfile>redhat</activeProfile>
            </activeProfiles>
          </settings>