apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: devspaces-user-config
spec:
  labelSelector:
    matchLabels:
      app.kubernetes.io/component: workspaces-namespace
  templates:
  - objectTemplate: |
      apiVersion: v1
      data:
        custom-ca-certificates.pem: |
          -----BEGIN CERTIFICATE-----
          MIIDgzCCAmugAwIBAgIECKIoeTANBgkqhkiG9w0BAQsFADByMQswCQYDVQQGEwJD
          WjEUMBIGA1UECBMLUHJhaGEtWmFwYWQxEDAOBgNVBAcTB1Jldm5pY2UxFTATBgNV
          BAoTDERldlNwYWNlc1BPQzEMMAoGA1UECxMDTldHMRYwFAYDVQQDEw1BbnRvbiBH
          aWVydGxpMB4XDTIzMDEyOTE1NTAzOFoXDTIzMDQyOTE1NTAzOFowcjELMAkGA1UE
          BhMCQ1oxFDASBgNVBAgTC1ByYWhhLVphcGFkMRAwDgYDVQQHEwdSZXZuaWNlMRUw
          EwYDVQQKEwxEZXZTcGFjZXNQT0MxDDAKBgNVBAsTA05XRzEWMBQGA1UEAxMNQW50
          b24gR2llcnRsaTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKi+swQN
          B0PJbH+c5nKV+V2MIRGlRn7hjSw+emeV56pbbyRy81N9u1sb5b6uUyL7JjhE9cIp
          LChdNqVlRpuhHQU7UbX5G6/ZKgnNMPyQ3o7JQGiQULGUoq2FHOBfVFkPF68TM848
          eQ/yZr+AXHlDpGBhlZ0SQ0+8xrhCJBF9X1vgGcI98T33y74vAfjTCOjuiycV+L9u
          t1cXiakVLmB9q0Ju1wJ3NAxZssvbWADr4A/befPpBOhccvsZFblikunw2l/gkgdq
          UBCbP1Mnh5K0Yy5YeEgrM3QhsDxLapzufpTQuL4It4yzdwnLBJJnFnISQD2riAQw
          7t/upCQLZTlJBYcCAwEAAaMhMB8wHQYDVR0OBBYEFNE0WmuouLedBc/cQtzmRcAP
          T9OiMA0GCSqGSIb3DQEBCwUAA4IBAQA7+gyuEoiRp9XdumUlQxmvoj9DCxR4cOW9
          /D/TzCM+jqnE3jKVbFwAR8jA9AssjA8jqzoSutMzJk5vSCBQ/z/Bugyp4md4uxu0
          R52j2kyuIFUxWDuQKRwx79tzvXS3FeHCnB7jIRuN6dP0dHzWmUWXKuPaRI0NKV3z
          K+9/XQoJIW2JbffTZBId0Bx0lO9xP7TJZ9xGM0Clb1VVVQo6zkxNMdfR/fGGU/U8
          SL6/j2unaduRC/xXPPYKIxcCqODtc6Mlr4czVAWl8BIJmVc8FmSlM1efo7QEsVYz
          j2MCowaMGJMDUTdVj/HTTmWUULc1cHpXly5BEP1vtwCRwKoUoQDJ
          -----END CERTIFICATE-----
      kind: ConfigMap
      metadata:
        labels:
          app.kubernetes.io/component: ca-bundle
          app.kubernetes.io/part-of: che.eclipse.org
        name: custom-ca-certificates
        namespace: {{ .Name }} 
  - objectTemplate: |
      kind: ConfigMap
      apiVersion: v1
      metadata:
        namespace: {{ .Name }} 
        name: settings-xml
        annotations:
          controller.devfile.io/mount-as: subpath
          controller.devfile.io/mount-path: /home/user/.m2
        labels:
          controller.devfile.io/mount-to-devworkspace: 'true'
          controller.devfile.io/watch-configmap: 'true'
      data:
        settings.xml: |
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <localRepository />
            <interactiveMode />
            <offline />
            <pluginGroups />
            <mirrors />
            <proxies />
            <profiles>
                <profile>
                  <id>redhat</id>
                  <repositories>
                      <repository>
                        <id>rh-ga</id>
                        <name>Red Hat public maven repo</name>
                        <url>https://maven.repository.redhat.com/ga/</url>
                        <releases>
                            <enabled>true</enabled>
                            <updatePolicy>never</updatePolicy>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                      </repository>
                      <repository>
                        <id>jenkins-ga</id>
                        <name>jenkins repo</name>
                        <url>https://repo.jenkins-ci.org/releases/</url>
                        <releases>
                            <enabled>true</enabled>
                            <updatePolicy>never</updatePolicy>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                      </repository>
                  </repositories>
                  <pluginRepositories>
                      <pluginRepository>
                        <id>rh-ga</id>
                        <name>Red Hat public maven repo</name>
                        <url>https://maven.repository.redhat.com/ga</url>
                        <releases>
                            <enabled>true</enabled>
                            <updatePolicy>never</updatePolicy>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                      </pluginRepository>
                  </pluginRepositories>
                </profile>
            </profiles>
            <activeProfiles>
                <activeProfile>redhat</activeProfile>
            </activeProfiles>
          </settings>