apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: namespace-config-operator
  namespace: namespace-config-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: alpha
  installPlanApproval: Automatic
  source: community-operators
  sourceNamespace: openshift-marketplace
  name: namespace-configuration-operator