apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: artemis-config-template
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      labels:
        app: artemis-config
      name: artemis-config
    data:
      destinationType: ${DESTINATION_TYPE}
      destination: ${DESTINATION}
      routeId: ${ROUTE_ID}
parameters:
  - name: DESTINATION_TYPE
    required: true
  - name: DESTINATION
    required: true
  - name: ROUTE_ID
    required: true  