ready: false # // CHANGE ME to true when you are ready to start Lab5
userNamespace: userN-dev # // CHANGE ME !!!
# Add as many entries below as many users you want to interact with
# Below are two working examples - please make sure to adjust names and destinationName according to your user name.
bindings:
 - name: rhte-camelk.user1.to.user2
   secret: artemis-credentials-secret
   sslSecret: client-truststore
   source:
    kamelet: timer-source-with-header
    properties:
     userName: user1
     message: greetings-from-red-hat-tech-exchange
   sink:
     kamelet:  custom-jms-amqp-10-sink
     properties:
      destinationName: user2-dev
      destinationType: topic
      password: "{{amqp.password}}"
      remoteURI:  "{{amqp.broker-url}}"
      trustStorePassword: "{{amqp.trustStorePassword}}"
      username: "{{amqp.username}}"

 - name: rhte-camelk.user1.to.log
   secret: artemis-credentials-secret
   sslSecret: client-truststore
   source:
     kamelet: custom-jms-amqp-10-source  
     properties:
      destinationName: user1-dev
      destinationType: topic
      password: "{{amqp.password}}"
      remoteURI:  "{{amqp.broker-url}}"
      trustStorePassword: "{{amqp.trustStorePassword}}"
      username: "{{amqp.username}}"             
   sink:
     kamelet: log-sink
     properties:
       showHeaders: true
