ready: false # // change me to true when you are ready to start lab3
userNamespace: usern-dev # // change me !!!
# add as many entries below as many users you want to interact with
# last binding is the one which reads messages from your user topic and prints the messages in it. you need to pass property showheaders with value true to the log kamelet(!)
bindings:
#  - name: rhte_camelk_usern_to_userm
#    secret: name_of_credentials_secret
#    sslSecret: secret_with_client.ts
#    source:
#     kamelet: name_of_custom_timer_kamelet
#     properties:
#      userName: name_of_your_user
#      message: any_special_message_to_share?
#    sink:
#      kamelet:  name_of_custom_amqp_sink_kamelet
#      properties:
#       destinationName: target_user (syntax; userN-dev)
#       destinationType: topic
#       remoteURI: "{{amqp.broker-url}}"
#       username:  "{{amqp.username}}"
#       password:  "{{amqp.password}}"
#       trustStorePassword: "{{amqp.trustStorePassword}}"


#  - name: rhte-camelk.usern.to.log
#    secret: name_of_credentials_secret
#    sslSecret: secret_with_client.ts
#    source:
#      kamelet: name_of_custom_source_kamelet  
#      properties:
#       destinationName: name_of_your_user
#       destinationType: topic
#       password: "{{amqp.password}}"
#       remoteURI:  "{{amqp.broker-url}}"
#       trustStorePassword: "{{amqp.trustStorePassword}}"
#       username: "{{amqp.username}}"                
#    sink:
#      kamelet: log-sink
#      properties:
#        showHeaders: true
