= camel-k crash course
include::_attributes.adoc[]

NOTE: Feel free to skip this page if you are already an experienced camel-k hacker

IMPORTANT: Please note this is not a definitive guide on camel-k. It's merely an extract of selected camel-k parts useful in context of this lab. For complete camel-k guide refer to the https://camel.apache.org/docs/[official documentation]

== Architecture

image::camel-k-high-level.svg[Camel-K High Level Architecture,title="Camel-K High Level Architecture"]

While the diagram above can be somewhat overwhelming, from a developer perspective you are abstracted from vast majority of all these implementation details. They will of course come handy during troubleshooting or when satisfying general developer curiosity.

The main parts of the camel-k platform are:

 - operator
 - runtime
 - traits
 - tooling


== Operator

Operator takes care of coordinating all the moving parts. Most importantly it takes care of translating Camel Integration (written mostly in java or yaml dsl by developers) into a running container image which includes Quarkus application with camel routes. It uses number of Customer Resources (CR) to achieve this. Here are some notable ones:

 * IntegrationPlatform
 ** Controls the behavior of the operator. Allows to configure maven settings, based image for builds, container registry and many others.
 * Integration
 ** Describes the application by listing sources, resources, dependencies and by providing configuration options. This is the CR which gets created whenever you run `kamel run` and it is defacto the openshift native descriptor of an camel integration.
 * IntegrationKit
 ** Fundamental side resource which describes a container image created by the camel-k operator as well as the configurations that need to be applied to every integration that is executed on top of it. An IntegrationKit does not include any source code or resource file defined by the Integration from which it has been generated.
 ** Even though completely hidden, this is a crucial CR for developers. Whenever you submit an Integration to the cluster, camel-k operator will analyze  and maintain it's dependencies. If there is an existing IntegrationKit CR which includes the same dependencies it will be automatically reused. This is one of the reason why camel-k offers such a good developer experience in the cloud environment - the hot redeploy feature works almost as good as in a traditional local dev environment. If you are submitting an Integration for the second time, and you are not changing its dependencies, but only source code, an already existing image (described by IntegrationKit) will be reused and the source code will be mounted via ConfigMap to the new pod. This means the subsequent Integration redeployments takes only couple of seconds instead of minutes!
* Kamelet (*Kamel* route snipp *ets* )
** Fundamental unit of abstraction describing integration with external system via simplified interface. Kamelets may contain integration logic consisting of multiple complex steps but they are consumed via simplified interface. All the consumer of kamelets see is expected parameters, input and output. The complex integration logic is completely hidden away. 
** Kamelet does not translate to a running Integration Application on its own. It's only a descriptor. They can be used in KameletBinding, Integration, but (maybe surprisingly) even in "old school" Camel on Spring Boot and Camel Quarkus application.
** Kamelet can be of *sink* type which is used for sending data to external systems, or of *source* type which is used for consuming data from external systems.

* KameletBinding
** Resources which allows to use (or bind) Kamelets to various resources(systems), which includes:
 *** KNative destination
 *** Kafka Topic
 *** Explicit URI (i.e. https://mycompany.com/the-service
 *** Another Kamelet

== Runtime

The main purpose of the camel-k runtime is to launch a Camel Quarkus java application which contains camel routes configured by the user. It takes care of things like sources loading, properties setting, and many more. While the fact Quarkus is the target runtime platform can be considered as an implementation detail,  it's useful to keep in mind that it allows for configuring certain aspects in the usual Quarkus-like way. For example, to enable debug logging for a specific logging category you could simply do `kamel run Integration.java -p quarkus.log.category."org.apache.kafka".level=DEBUG`

== Traits

Traits are used to _tune_ specific aspects of Integration. camel-k platform also uses traits to perform many common (but hidden) operations which are essential for running an Integration successfully. These are called *platform traits* and should never be disabled. The list of traits is constantly growing and can be found in the https://camel.apache.org/camel-k/1.11.x/traits/traits.html[documentation]. Examples could be `container`, `jvm`,`logging`,`kubernetes`, `tracing`, etc.
Example usage:
 `kamel run --trait container.limit-cpu=2 Integration.java`

 
== CLI

https://github.com/apache/camel-k/releases[`kamel` CLI] is a fundamental part of the `camel-k` developer experience. It is the go-to tool for the early stages of camel-k development. It can also be easily embedded in your favourite CI tool such as Jenkins or Tekton to run `kamel run` or `kamel promote` operations. Note it is _really_ important to make sure your version of `kamel` CLI is in sync with the camel-k operator version. This is because the product is evolving really quickly and breaking API/CRD changes are not so rare. In the out-of-sync scenarios it can happen that `kamel` will produce Integration CR which will be incompatible with the Integration CRD expected by the camel-k operator.
