= Welcome to camel-k : Beyond Demo lab
:page-layout: home
:!sectids:

[.text-center.strong]
== Lab intro

Welcome to Cloud Native Integration with camel-k lab. We are excited to have you. The focus of this lab is to share field experience from real, production, camel-k deployment. We will not be focusing on the creation of the complex camel integration. Instead, we will be focusing on everything else - building, deploying, testing, troubleshooting and customizing. The aim is to cover a full lifecycle of developing a camel-k application. From the initial bootstrapping all the way to production deployment. Let's get down to it, and most importantly, let's have some fun.

== Lab Goals
The primary goal of this lab is to enable Red Hat consultants and architects to deliver camel-k projects for our customers beyond the demo scope. We want our attendees to understand all the parts of the camel-k development lifecycle. Including initial local development, dev deployment, troubleshooting, extending the out of the box bits, production deployment. The primary difference between demo and a the real engagement is the environment and its constraints - such as authentication, security, internet access, immutability, supportability, etc.. The lessons learned in this lab are based on real engagement at large UK customer (Motability) which went successfully live.

[.tiles.browse]
== Browse modules

[.tile]
* xref:01-setup.adoc[Environment setup and class orientation]

[.tile]
* xref:lab1.adoc[Lab 1 - Local Development]

[.tile]
* xref:lab2.adoc[Lab 2 - Customizing Kamelets]

[.tile]
* xref:lab3.adoc[Lab 3 - KameletBinding evolution]

[.tile]
* xref:lab4.adoc[Lab 4 - Traditional CI/CD]

[.tile]
* xref:lab5.adoc[Lab 5 - GitOps styled Continuous Delivery]
