ready: false # // CHANGE ME to true when you are ready to start Lab5
userNamespace: userN-prod # // CHANGE ME !!!
# Add as many entries below as many groups you want to interact with
# Below are two working examples - please make sure to adjust names and destinationName according to your group name.
bindings:
 - name: rhte-camelk.group1.to.group2
   secret: artemis-credentials-secret
   sslSecret: truststore-secret
   source:
    kamelet: timer-source-with-header
    properties:
     groupName: group1
     message: greetings-from-red-hat-tech-exchange
   sink:
     kamelet:  custom-jms-amqp-10-sink
     properties:
      destinationName: group2-prod
      destinationType: topic
      password: "{{amqp.password}}"
      remoteURI:  "{{amqp.broker-url}}"
      trustStorePassword: "{{amqp.trustStorePassword}}"
      username: "{{amqp.username}}"

 - name: rhte-camelk.group1.to.log
   secret: artemis-credentials-secret
   sslSecret: truststore-secret
   source:
     kamelet: custom-jms-amqp-10-source  
     properties:
      destinationName: group1-prod
      destinationType: topic
      password: "{{amqp.password}}"
      remoteURI:  "{{amqp.broker-url}}"
      trustStorePassword: "{{amqp.trustStorePassword}}"
      username: "{{amqp.username}}"             
   sink:
     kamelet: log-sink
     properties:
       showHeaders: true