apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces-parent-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: devspaces-project
  source:
    path: argo-apps/tooling-app-of-apps
    repoURL: https://github.com/agiertli/devspaces.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
