apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhte-camelk-tooling-app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: rhte-camelk-tooling
  source:
    path: argo-apps/tooling-app-of-apps
    repoURL: https://github.com/agiertli/rhte-camelk-lab-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true