apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devspaces-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: ArgoCD Project for Tooling
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
