spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/agiertli/devspaces.git
    targetRevision: HEAD
argo:
  namespace: openshift-gitops
  destination: tooling
  project: mw-day-tooling      

applications:
   - name: devspaces-install
     path: devspaces-install
     destination: devspaces
   - name: namespace-config
     path: namespace-operator
     destination: namespace-config-operator
