spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/agiertli/devspaces.git
    targetRevision: HEAD
argo:
  namespace: openshift-gitops
  destination: tooling
  project: devspaces-project      

applications:
   - name: argocd-rbac
     path: rbac
     destination: openshift-gitops

  #  - name: devspaces-install
  #    path: devspaces-install
  #    destination: devspaces
     
  #  - name: namespace-config
  #    path: namespace-operator
  #    destination: namespace-config-operator
