---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-k-pipeline-rb
subjects:
  - kind: ServiceAccount
    name: camel-k-pipeline-sa
    namespace: user1-dev
roleRef:
  kind: Role
  # Either reuse this role, or, define a role with the least privileges required
  name: camel-k-operator
  apiGroup: rbac.authorization.k8s.io