{{- range $key := .Values.bindings }}
---
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: >- 
   {{ .name }}
  namespace: {{ $.Values.userNamespace }} 
spec:
  replicas: {{ if kindIs "float64" .replicas }}{{ .replicas }}{{ else }}{{ 1 }}{{ end }}
  integration:
    traits:
      container:
        configuration:
          limitCPU: {{ .cpuLimit | default "100m" }}
          requestCPU: {{ .cpuRequest | default "10m" }}
          limitMemory: {{ .memoryLimit | default "374Mi" }}
          requestMemory: {{ .memoryRequest | default "256Mi" }}
      mount:
        {{ if .sslSecret }}
        resources:
          - 'secret:{{ .sslSecret }}@{{ .sslMountPath | default "/etc/ssl/certificates" }}' 
        {{ end }}

        {{ if .secret }}
        configs:
          - 'secret:{{ .secret }}'
        {{ end }}       
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: {{ .source.kamelet }}
    properties:
      {{- range $k,$v := .source.properties }}
        {{ $k }}: {{ printf "\"%s\"" $v }}
        {{- end}}
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: {{ .sink.kamelet }}
    properties:
      {{- range $k,$v := .sink.properties }}
          {{ if eq $k "showHeaders"}}
        {{ $k }}: {{ $v }}
           {{ else }}
        {{ $k }}: {{ printf "\"%s\"" $v }}
         {{ end }}
      {{- end}}
{{- end }}