{{- range $key := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.argo.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .destination }}
    server: {{ $.Values.spec.destination.server }}
  project: {{ $.Values.argo.project }}
  source:
    path: argo-apps/{{ .path }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
     - SkipDryRunOnMissingResource=true
    automated:
      selfHeal: true
{{- end }}