apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-custom-rolebinding
  namespace: openshift-gitops
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: ClusterRole 
  name: custom-argocd-role
  apiGroup: rbac.authorization.k8s.io