apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: openshift-gitops
  name: custom-argocd-role
rules:
- apiGroups: 
   - sonatype.com
  resources: 
    - NexusRepo
  verbs: 
   - '*'
- apiGroups: 
   - redhatcop.redhat.io
  resources: 
    - namespaceconfigs
    - namespaceconfig
  verbs: 
   - '*'
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusters
  - checluster
  verbs:
  - '*'      
