apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-custom-rolebinding
  namespace: openshift-gitops
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
roleRef:
  kind: Role 
  name: custom-argocd-role
  apiGroup: rbac.authorization.k8s.io